### ISSUE TITLE
Issue with docs/setup/kubernetes/install/helm/index.md

### ISSUE THREAD

**Issue by Aisuko** [istio/istio.io#4823] opened 2019-08-24 13:37 UTC
Please have a look at this https://istio.io/zh/docs/setup/kubernetes/install/helm/#%E6%96%B9%E6%A1%88-1-%E4%BD%BF%E7%94%A8-helm-template-%E8%BF%9B%E8%A1%8C%E5%AE%89%E8%A3%85 . the number of the istio's CRD is 53.

But there is a blog 2019 https://istio.io/blog/2019/evolving-istios-apis/#what-s-coming-next , and it said `in Istio 1.2.x we cut the number from 54 down to 23.`

So, please fix that ,replace 54 to 23, 58 to 28. thanks.

**Comment by linsun** [comment] 2019-09-05 13:50
Thanks for reporting this!  #4920

**Comment by linsun** [comment] 2019-09-09 12:58
Close this out since the PR is merged.  Please reopen if the issue isn't fixed.

**Closed by linsun** 2019-09-09 12:58 UTC
Labels: area/environments, kind/docs

**Comment by Aisuko** [comment] 2019-09-09 15:36
There may need to fix the numbers of CRD which in the second plan. But I can not reopen my issue. So, there need to refer to the new issue.
