### ISSUE TITLE
Need to automate testing the ambient L4 user guide

### ISSUE THREAD

**Issue by linsun** [istio/istio.io#14253] opened 2023-12-04 14:51 UTC
https://istio.io/latest/docs/ops/ambient/usage/ztunnel/

Current test is no.

It is also hard to know which steps work or not, as hairpin is not fully implemented in ambient and the guide talks about it.

**Comment by srampal** [comment] 2024-01-08 17:11
Duplicate of the earlier issue ... will be tracked there ...

https://github.com/istio/istio.io/issues/14117

**Closed** 2024-01-08 17:26 UTC
Labels: community/good first issue, area/ambient, good first issue
