### ISSUE TITLE
istio 1.4 docs sidebar is not functioning properly

### ISSUE THREAD

**Issue by carolynhu** [istio/istio.io#6844] opened 2020-03-10 17:24 UTC
When I browse through https://archive.istio.io/v1.4/docs/
The sidebar is not clickable, thus, it cannot redirect me to the corresponding sections.
![Screen Shot 2020-03-10 at 10 23 09 AM](https://user-images.githubusercontent.com/29208297/76340689-3f60c600-62b9-11ea-9237-cda15579fe9b.png)

**Comment by geeknoid** [comment] 2020-03-10 21:22
Dupe of #6820

**Closed by geeknoid** 2020-03-10 21:22 UTC
