### ISSUE TITLE
Can not see "Safely Upgrade Istio... Document"

### ISSUE THREAD

**Issue by findstar** [istio/istio.io#7470] opened 2020-06-04 13:42 UTC
On https://istio.io/blog/2020/multiple-control-planes/

2020 Post "Safely Upgrade Istio using a Canary Control Plane Deployment"

I can not see "google slides"

https://docs.google.com/presentation/d/e/2PACX-1vSbj4B52oEtQ8wGvmaSy29Zao3Q8Ex-w6JaripuJThMTK4F4bxDZkyNUSaexz8Rp8v4QCuDB2dAZkrv/embed?start=false&loop=true&delayms=3000

It need to change visibility to public.

**Comment by shamsher31** [comment] 2020-06-05 10:11
Duplicate of https://github.com/istio/istio.io/issues/7374

**Closed by shamsher31** 2020-06-05 10:11 UTC
