### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by MingYuanTomas** [istio/istio.io#15783] opened 2024-10-10 10:01 UTC
https://istio.io/latest/docs/tasks/traffic-management/mirroring/

```shell
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
- httpbin
  http:
  - route:
- destination:
    host: httpbin
    subset: v1
  weight: 100
mirror:
  host: httpbin
  subset: v2
mirrorPercentage:
  value: 100.0
EOF
```
file content error

**Comment by zirain** [comment] 2024-10-11 02:33
@kfaseela looks like same issue last time you ask me? related to the tabset?

**Comment by kfaseela** [comment] 2024-10-11 04:54
> @kfaseela looks like same issue last time you ask me? related to the tabset?

Yeah looks like the same..

**Comment by kfaseela** [comment] 2024-10-11 08:30
Duplicate of https://github.com/istio/istio.io/issues/15689

**Closed** 2024-10-11 08:30 UTC
Labels: good first issue
