### ISSUE TITLE
Undefined/unlinked terms on docs/reference/config/metrics/index.md

### ISSUE THREAD

**Issue by dsbos** [istio/istio.io#8722] opened 2020-12-31 15:05 UTC
The page currently at https://istio.io/latest/docs/reference/config/metrics/ refers to `COUNTER` and `DISTRIBUTION` without ever defining what those are or linking those references to some definitions of those terms.

**Comment by esnible** [comment] 2021-03-04 20:12
Closing as a duplicate of https://github.com/istio/istio.io/issues/9027 (even though this issue was filed earlier).

**Closed by esnible** 2021-03-04 20:12 UTC
