### ISSUE TITLE
Istio 1.5.0 beta 3 doesn't come up when operator installation method is used

### ISSUE THREAD

**Issue by brian-avery** [istio/istio.io#6595] opened 2020-02-25 19:14 UTC
**Bug description**
When the Istio operator installation method is used on 1.5 beta 3 (https://preliminary.istio.io/docs/setup/install/standalone-operator/), then the Istio installation doesn't come up. Looking at the pods, several are complaining about missing configmaps. I tried this on Kubernetes 1.16.7, 1.17, and 1.14.2, all on Minikube 1.7.3. Attaching the kubectl describe from 1.16 and 1.14. 
[1.14_deploy.txt](https://github.com/istio/istio/files/4251688/1.14_deploy.txt)

**Expected behavior**
Istio pods eventually come up

**Steps to reproduce the bug**
Install Istio according to the instructions for the operator. 
[1.14_deploy.txt](https://github.com/istio/istio.io/files/4251702/1.14_deploy.txt)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
https://preliminary.istio.io/docs/setup/install/standalone-operator/

**Environment where bug was observed (cloud vendor, OS, etc)**
Minikube 1.7.3
Kubernetes: 1.14.2, 1.16.7, 1.17
Istio: 1.5.0 beta 3

[1.14_deploy.txt](https://github.com/istio/istio.io/files/4251703/1.14_deploy.txt)

**Comment by dgn** [comment] 2020-02-28 10:06
@brian-avery this is caused by https://github.com/istio/istio/issues/21463

**Comment by dgn** [comment] 2020-03-03 10:44
@brian-avery could you verify this is fixed with 1.5.0-beta.5?

**Comment by johnma14** [comment] 2020-03-03 18:06
@dgn @brian-avery I tested this on docker-desktop and it works fine. There are 2 minor issues related to this task but those are doc issues.

**Comment by dgn** [comment] 2020-03-04 12:43
> @dgn @brian-avery I tested this on docker-desktop and it works fine. There are 2 minor issues related to this task but those are doc issues.

Thank you for verifying, this matches what I saw in my own tests. Closing this

**Closed by dgn** 2020-03-04 12:43 UTC
Labels: area/environments, community/testing days
