### ISSUE TITLE
Supported EKS versions for Istio 1.6 Missing

### ISSUE THREAD

**Issue by kjowong** [istio/istio.io#10319] opened 2021-09-09 20:15 UTC
Looks like the EKS supported versions for Istio 1.6 is missing in the supported release section: https://github.com/istio/istio.io/blob/master/content/en/docs/releases/supported-releases/index.md

Does Istio 1.6 still support up to EKS 1.18? My team has that documented to track dependencies since we are in the process of updating EKS versions and working with the team that updates our Istio versions.

**Comment by ericvn** [comment] 2021-09-09 21:28
The values are missing by design. When the table was added, the Kubernetes versions were specified for all of the community supported Istio versions. Istio 1.6 is no longer a supported version.

You can fall back to the old way of looking at what was tested by looking at the install page from that version of the documentation. For example, for 1.6 you can go to https://istio.io/v1.6/docs/setup/install/. That shows that we tested Istio 1.6 with Kubernetes 1.15 to 1.18.

**Comment by ericvn** [comment] 2021-09-20 13:47
Closing this issue as answered. If you have additional questions, please re-open the issue. Thanks.

**Closed by ericvn** 2021-09-20 13:47 UTC
