### ISSUE TITLE
MTLS encryption is not working with default configuration.

### ISSUE THREAD

**Issue by RM250702** [istio/istio.io#10536] opened 2021-11-23 08:48 UTC
1) installed with helm charts
2) Istio version 1.11.3
3) side car injection enabled namespace wide for all the pods
4) Peer authentication is enabled as STRICT.
5) Rabbitmq cluster is also installed in the same namespace and has side car injected
FLOW SCENARIO.
1) Simulator (creates fake transactions that will be sent to the pod in the istio enabled cluster and this pod will forwards the traffic to rabbitmq pods).
CURRENT RESULTS.
using ksniff and wireshark to sniff the tcpdump.
also, the same plain text is seen when i ran sudo tcpdump command in istio-proxy sidecar.
![github_issue](https://user-images.githubusercontent.com/76467939/142993772-6e09b735-63ae-4817-a471-320cfa686882.PNG)
EXPECTED RESULTS
need to see entire traffic to be encrypted.

**Comment by ericvn** [comment] 2021-11-23 15:12
Closing this as a duplicate of https://github.com/istio/istio/issues/36219.

**Closed by ericvn** 2021-11-23 15:12 UTC
Labels: area/networking
