### ISSUE TITLE
Why your official website crash frequently?

### ISSUE THREAD

**Issue by Huixxi** [istio/istio.io#11859] opened 2022-09-09 03:43 UTC
It's too hard to look up your official documents because it is often in an inaccessible state. Could you please do something to ensure its stability? Thanks.

**Comment by ericvn** [comment] 2022-09-09 14:07
@davidhauck or maybe @craigbox Would this be something with Netlify?

**Comment by craigbox** [comment] 2022-09-11 23:44
Hi @Huixxi 

Can you give me any more detail on what the problem is?  I've heard the animation on https://istio.io/ uses a lot of CPU in some cases but no other problems on any other pages have been reported. 

Please let me know.

-c

**Comment by rootsongjc** [comment] 2022-09-13 09:32
@Huixxi What's your network environment? Do you access from our organization's firewall? Sometimes the website with `.io` suffix will be blocked in some organizations in China.

**Comment by craigbox** [comment] 2022-09-13 23:43
Can you record a video of it happening?  Or maybe capture a HAR file in Chrome? I would love to fix whatever problem you are having but have no way to know what it is.

https://toolbox.googleapps.com/apps/har_analyzer/

**Comment by Huixxi** [comment] 2022-09-15 07:28
> Can you record a video of it happening? Or maybe capture a HAR file in Chrome? I would love to fix whatever problem you are having but have no way to know what it is.
> 
> https://toolbox.googleapps.com/apps/har_analyzer/

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/21335093/190342129-66137055-1861-49ab-98b8-48ac0e0c855a.png">

**Comment by Huixxi** [comment] 2022-09-15 07:30
> Can you record a video of it happening? Or maybe capture a HAR file in Chrome? I would love to fix whatever problem you are having but have no way to know what it is.
> 
> https://toolbox.googleapps.com/apps/har_analyzer/

This site can’t be reachedThe webpage at https://istio.io/latest/docs/setup/additional-setup/gateway/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by Huixxi** [comment] 2022-09-15 09:14
> Can you record a video of it happening? Or maybe capture a HAR file in Chrome? I would love to fix whatever problem you are having but have no way to know what it is.
> 
> https://toolbox.googleapps.com/apps/har_analyzer/

This page isn’t workingistio.io didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by craigbox** [comment] 2022-09-15 10:16
I'm sorry for the hassle, @Huixxi.
Istio's web site is hosted with Netlify.com and we have no information about it being inaccessible to anyone else, or indeed any other site on Netlify being down.

As @rootsongjc mentions the error message makes it seem like the problem is with your VPN proxy.  I am going to close this issue because there doesn't seem to be anything wrong for multiple users and unfortunately there is very little we can do to help.

You could try [preliminiary.istio.io](https://preliminary.istio.io/) which is the current master branch, and see if that works when istio.io does not.

**Closed by craigbox** 2022-09-15 10:16 UTC
