### ISSUE TITLE
[1.5 Community Testing] Configuration Profiles guide needs to be updated to reflect the latest set of profiles

### ISSUE THREAD

**Issue by johnma14** [istio/istio.io#6713] opened 2020-03-03 22:59 UTC
In this section of the docs: https://preliminary.istio.io/docs/setup/additional-setup/config-profiles/, it still refers to 5 profiles:
- default
- demo
- minimal
- sds
- remote

whereas when we do a `istioctl profile list`, it displays 6 profiles:
- default
- demo
- minimal
- seperate
- remote
- empty

I am pretty sure there was a bug opened for this issue but I cannot find it anymore. Opening this in case that got closed as fixed, since I am seeing this issue using the beta-5 build. Thanks.

**Comment by shamsher31** [comment] 2020-03-04 14:45
Thanks @johnma14 for catching this.

**Comment by frankbu** [comment] 2020-03-04 15:24
Duplicate of #6645

**Closed by frankbu** 2020-03-04 15:24 UTC
Labels: community/testing days

**Comment by johnma14** [comment] 2020-03-04 15:58
Thanks @frankbu.
