### ISSUE TITLE
SCTP Protocol is not supported in istio config

### ISSUE THREAD

**Issue by dnelaturi** [istio/istio.io#9513] opened 2021-04-12 15:25 UTC
Hi, 

We have telecom products and most of them are based on tcp/ip for internal communication however the front-ending application/ communication with external world uses sctp based connections. 
And istio doesn't support sctp. However kuberentes does support sctp at pod and service level.

I would like to understand if there a plan to add sctp support in Istio.

Thank You
Daniel Raj.

**Comment by howardjohn** [comment] 2021-04-12 17:16
Dupe of https://github.com/istio/istio/issues/32118. thanks

**Closed by howardjohn** 2021-04-12 17:16 UTC
