### ISSUE TITLE
 https://git.io/getLatestIstio gets 1.0.6

### ISSUE THREAD

**Issue by utka** [istio/istio.io#3325] opened 2019-02-21 17:26 UTC
https://preliminary.istio.io/docs/setup/kubernetes/download-release/ 
Wrong istio version

**Comment by geeknoid** [comment] 2019-02-21 18:06
This is expected behavior as 1.1 is not released yet. The script always installs the latest released version.

@sdake @costinm Any ideas on how to make this better? Should we publish a different script for each version and point the web site to that? So instead of getLatestIstio it would be getIstio-1-1, getIstio-1-2, etc.

**Comment by geeknoid** [comment] 2019-03-06 19:18
I don't know how stuff on git.io gets updated. But if instead, this script was located in the istio/istio repo, it could contain different stuff depending on the branch it's in. Then we can have the web site point to the appropriate branch for the doc set.

So maybe instead of getLatestVersion.sh, this is just getIstio.sh and it gets you the latest for the specific branch you're running it from.

**Comment by ldemailly** [comment] 2019-03-07 19:56
the script is in istio/istio and does already have provisions to download a specific version
as documented in the header

eg
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.0 sh -
```

btw see also https://github.com/istio/istio/pull/11028#issuecomment-470669763

**Comment by linsun** [comment] 2019-03-08 18:50
remaining of this is to ensure this script can download 1.1 when it is out.

**Comment by geeknoid** [comment] 2019-03-08 18:53
Let's fix this in a way this automatically works across doc releases so
won't need to do anything manual.

**Comment by ldemailly** [comment] 2019-03-08 19:11
the script will download 1.1 automatically as soon as the release is marked as released and not pre release (read the code)

**Comment by geeknoid** [comment] 2019-03-08 19:17
What I mean is that I'd like to download the version of the product
associated with the doc set. So the 1.1 docs always show how to download
the 1.1 binaries, even after 1.2 is released.

**Comment by sdake** [comment] 2019-03-12 10:24
@geeknoid how about something like

```curl -L https://git.io/getLatestIstio | ISTIO_VERSION={{ insert_doc_branch_version_here }} sh -```

Where the documentation site automatically inserts the latest z stream from whatever y stream the docs branch is on?  IOW istio.io latest release is 1.0.6 - istio.io docs website is at release-1.0, istio.io docs website pulls the latest release tag for its z stream (which in this case is 1.0.6) and automatically inserts in the documentation?

No idea where this git.io server serves stuff from.  Anyone have a link to the getLatestIstio script?

cheers
-steve

**Comment by geeknoid** [comment] 2019-03-12 12:33
Here's a braindump:

- git.io is a URL shortener run by GitHub. I don't know how easy it is to update a link already in there.

- git.io/getIstio points to https://raw.githubusercontent.com/istio/istio/master/downloadIstio.sh
 
- PR istio/istio#11028 deleted downloadIstio.sh, breaking the aforementioned getIstio short link.

- git.io/getLatestIstio points to https://raw.githubusercontent.com/istio/istio/master/release/downloadIstioCandidate.sh

- We need a scheme where the doc site doesn't need manual updating for every release, and where the doc page will remain functional even when the site is archived (so that the 1.1 archive continues to install Istio 1.1 even though we're now in Istio 1.23)

Given the above can we do this:

- Create istio/istio/release/getIstio.sh which gets a version of Istio, defaulting to the current branch latest patch. So getIstio.sh in the release-1.1 branch gets the latest patch of 1.1. getIstio.sh in the release-1.2 branch gets the latest patch of 1.2, etc.

- Have the command-line in istio.io locked to the version documented by the site. So it would point to raw.githubusercontent.com/istio/istio/<branch>/release/getIstio.sh

- Delete git.io/getLatestIstio and git.io/getIstio. No need for this voodoo since users can just cut & paste from the istio.io doc page.

- Delete istio/istio/release/downloadIstioCandidate.sh.


How's that?

**Comment by ldemailly** [comment] 2019-03-13 16:36
you can't update git.io links, it's write only by design (otherwise it would need some kind of permission and account management which afaik it does not)

personally I do think the short url is more valuable than a long script copy paste so I would maintain them rather than get rid of them but that's up to you (I also don't think it's really a huge deal that the doc install by default gets the latest released version, you could have an automation on archived ones that adds the correct ISTIO_VERSION like @sdake mentioned

**Comment by sdake** [comment] 2019-03-14 13:40
@geeknoid the bad news is that if we intend to solve this before Friday - we would have to potentially spin a new release candidate, which we really don't want to do to implement your proposal.

A middle ground is to implement this post-release and backport the script you propose. (meaning this issue would trail the 1.1 release).

Cheers
-steve

**Comment by dwradcliffe** [comment] 2019-03-14 14:26
Throwing in my opinion here, but I think it's completely reasonable to have to pass in a version if you want something other than $latest. Maybe that means adding the proper ISTIO_VERSION variable to the install docs?

**Comment by geeknoid** [comment] 2019-03-14 15:01
OK, I guess we'll have to go with an explicit version indication.

I don't like the fact it's called getLatestIstio and yet you pass it a version number...

**Comment by dwradcliffe** [comment] 2019-03-14 15:05
> I don't like the fact it's called getLatestIstio and yet you pass it a version number...

New link: `downloadIstio`?

**Comment by duderino** [comment] 2019-03-14 18:30
@costinm @utka @sdake heads up, regardless of the mechanism, we need this ready to be flipped by end of day Friday (the actual flip will probably occur on Monday since we'd like to enjoy our weekend)

**Comment by geeknoid** [comment] 2019-03-14 18:50
I'm going deal with this today one way or another.

**Closed** 2019-03-14 20:52 UTC
Labels: area/environments, kind/docs
