### ISSUE TITLE
Start up instructions should mention cert files

### ISSUE THREAD

**Issue by vnugent** [istio/istio.io#2765] opened 2018-10-12 17:13 UTC
Starting up instructions should tell users cert files must already exist:  
 https://istio.io/docs/setup/kubernetes/platform-setup/minikube/

Unsuspecting new users (myself included) would likely copy and run the provided commands just to find out later minikube won't work without a valid ca.crt and ca.key.
```
minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 \
    --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
    --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
    --vm-driver=`your_vm_driver_choice`
```

**Comment by ibm-jason** [comment] 2019-02-04 15:14
@andraxylia, @vnugent - Issue bump. :-)

If there are no objections, I'm going to see if I can get a PR going for this issue.

**Comment by geeknoid** [comment] 2019-03-11 21:38
This is a P0 blocking the 1.1 release. When you believe this issue can be addressed? If you don't have time, please assign to someone else that can address this issue.

Thanks.

**Comment by ibm-jason** [comment] 2019-03-11 21:39
@geeknoid I'll ask for the best option we have here, and submit the PR ASAP.

**Comment by linsun** [comment] 2019-03-12 01:09
is this a prob?  I can't recreate it on Mac.  Basically, it is using minikube self signed certs.  Check out:  https://github.com/kubernetes/minikube/issues/1647#issuecomment-311138886

Please try recreate this on latest minikube.  I'm using

```
$ minikube version 
minikube version: v0.34.1
```

**Comment by linsun** [comment] 2019-03-12 01:09
@vnugent @ibm-jason ^^

**Comment by linsun** [comment] 2019-03-12 01:13
BTW, this is changed to use https://preliminary.istio.io/docs/setup/kubernetes/prepare/platform-setup/minikube/ in 1.1

**Comment by linsun** [comment] 2019-03-12 01:14
@geeknoid I marked it as 1.0 because this is not an issue for 1.1

**Comment by ibm-jason** [comment] 2019-03-12 14:00
@linsun - I tried this out and you're correct- this does not affect 1.1.

**Comment by geeknoid** [comment] 2019-03-12 14:09
Closing...

**Comment by ibm-jason** [comment] 2019-03-12 14:09
@linsun Additionally, this cannot be created with the latest version of minikube, as you've suggested. When this issue was originally filed, the most recent version of minikube was [v.0.30.0](https://github.com/kubernetes/minikube/releases/tag/v0.30.0).

**Comment by sdake** [comment] 2019-03-12 14:43
fwiw, prior to 1.0 timeframe I could not reproduce this problem without cert config.  They cert config lneis were added prior to the 1.0 docs release and I think they have added confusion.  I'm not sure why they were added, or what the corrective action should be for this PR.

Is the extra config required?  @wattli @andraxylia 

The OP filed issue seems to indicate Istio does not function with them with older versions of minikube.  I'd like to remove them if not needed, however, if that is the root problem, will move to a P1.

Cheers
-steve

**Comment by ibm-jason** [comment] 2019-03-12 15:43
@sdake Here are the results from running the command w/o the extra configs:

```
minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 --vm-driver="virtualbox"
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubelet v1.10.0
Downloading kubeadm v1.10.0
Finished Downloading kubeadm v1.10.0
Finished Downloading kubelet v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...
Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
```

**Comment by wattli** [comment] 2019-03-12 17:46
1) It is a 1.0 issue and does not block 1.1 release
2) @sdake , what is the "OP filed issue"?

**Comment by vnugent** [comment] 2019-03-12 17:48
Yes this was 1.0 issue. I can't reproduce this in 1.1

**Comment by ibm-jason** [comment] 2019-03-13 03:03
@wattli, I'll defer to @sdake, but I think that "OP filed issue" = operator filed issue.

**Comment by sdake** [comment] 2019-03-13 05:25
Here is the issue as I understand it:

```minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 \
    --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
    --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
    --vm-driver=`your_vm_driver_choice````

is confusing.  Instead the command:

```
minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 \
    --vm-driver=`your_vm_driver_choice````

would not be confusing.  The question is, does this command work with Istio and bookinfo.  I tested this exact scenario in 1.0, and it worked for me.  Then the cert overrides were added back in, causing confusion as referenced by the 6 thumbs up on the OP (original poster)'s issue tracker.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-13 06:08
Here was my workflow:
```
minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 --vm-driver=vmwarefusion
cd istio-1.1.0-rc.4*
helm init --service-account tiller
helm version (wait for helm to init)
helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
(wait for crds to register)
minikube tunnel
kubectl label namespace default istio-injection=enabled
kubectl apply -f bookinfo.yaml
kubectl apply -f bookinfo-gateway.yaml
```

Here were the results:
<img width="1013" alt="Screen Shot 2019-03-12 at 10 59 00 PM" src="https://user-images.githubusercontent.com/755849/54257075-660be580-451b-11e9-9ad8-7f13b3a39767.png">

People are confused by the certs specified in the command line.  They don't make sense now, and I don't think they made sense in 1.0.

Might also help to document `minikube tunnel` such that people don't have to mess with nodeport.

Cheers
-steve

**Comment by sdake** [comment] 2019-03-13 06:12
> https://preliminary.istio.io/docs/setup/kubernetes/prepare/platform-setup/minikube/

@linsun - I missed your comment and didn't look at preliminary....

Moving to 1.0 and reducing priority.

MIght be helpful to document the minikube tunnel command as it is not obvious.

Cheers
-steve

**Closed** 2019-03-13 06:14 UTC
Labels: area/environments, kind/docs
