### ISSUE TITLE
doc.test.profile_default_istio.io test flaky

### ISSUE THREAD

**Issue by zirain** [istio/istio.io#12464] opened 2023-01-14 01:30 UTC
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12459/doc.test.profile_default_istio.io/1614012563471732736
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12455/doc.test.profile_default_istio.io/1613815126287192064

**Comment by ericvn** [comment] 2023-01-14 15:21
From the one job I looked at, it seems the job is taking to long so the whole test passes the list and fails:

```=== RUN   TestDocs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh/gtwapi_test.sh
2023-01-14T02:14:12.430092Z	info	tf	=== BEGIN: Test: 'tests_setup_profile_default[TestDocs/tasks/traffic-management/tcp-traffic-shifting/gtwapi_test.sh/gtwapi_test.sh]' ===
2023-01-14T02:14:12.430153Z	info	tf	Running command script gtwapi_test.sh
panic: test timed out after 1h0m0s
```

**Comment by ericvn** [comment] 2023-01-14 15:23
debug.out has:
```
+++__verify_with_retry(): snip_apply_weightbased_tcp_routing_4
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-6wbts -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec '' -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
++__verify_with_retry(): out='E0114 02:41:39.883594  180595 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0114 02:41:39.884330  180595 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0114 02:41:39.886287  180595 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0114 02:41:39.888117  180595 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0114 02:41:39.889838  180595 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by ericvn** [comment] 2023-01-14 15:29
Seems the test starts around 2:12 and it's 2:42 at this point so something is taking 30 mins?

Need to see if the other tests are failing similarly.

**Comment by kfaseela** [comment] 2023-01-15 13:04
Do we have to increase the test timeout from 1 hour? As we have been adding more tests.. or is there some test which is buggy that sometimes get stuck?

**Comment by ericvn** [comment] 2023-01-17 17:42
I think some tests gets stuck taking a long time, and that's blowing past the 1 hr. I do see in the job history: https://prow.istio.io/job-history/gs/istio-prow/pr-logs/directory/doc.test.profile_default_istio.io that the normal time when passing is 45-50 minutes. I still think one test, or maybe there is more than one, is taking a long time. In the past I found tests that were checking for certain items and occasionally they were out of order, so had to rewrite as checking for both items individually. Something like that could be happening here. Just need to find some time to dig through the logs and see if there is something that occurs more often that is causing the flake.

**Comment by ericvn** [comment] 2023-01-17 21:34
So I went back at starting by looking at the last 12 failures:
1 was the circuit breaking failure which has been a long-standing flake,
3 were the gateway-api_test.sh failing explicitly
3 timed out in the Istio-dashboard test
6 times out in the gateway-api_test.sh

**Comment by ericvn** [comment] 2023-01-17 21:41
Looking at the last 3 passes, the time for the /tcp-traffic-shifting/gtwapi_test.sh/gtwapi_test.sh  test averaged to about 70 secs. I will note that there few tests remaining, but it doesn't seem that we are close to the actual 60 minutes between test start and the panic.

**Comment by ericvn** [comment] 2023-01-17 22:09
Looking at the 6 gtwapi_test.sh failures they all appeared to have the logs above for the _verify_lines snip_apply_weightbased_tcp_routing_4 part of the script. 


If I look at the passing tests, there output has:
```
+++__verify_with_retry(): snip_apply_weightbased_tcp_routing_4
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
...
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-npslt -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-npslt -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-npslt -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
++__verify_with_retry(): out='command terminated with exit code 1
command terminated with exit code 1
command terminated with exit code 1
command terminated with exit code 1
command terminated with exit code 1
command terminated with exit code 1
one Mon Jan 16 04:43:14 UTC 2023
one Mon Jan 16 04:43:15 UTC 2023
one Mon Jan 16 04:43:16 UTC 2023
one Mon Jan 16 04:43:18 UTC 2023
one Mon Jan 16 04:43:19 UTC 2023
one Mon Jan 16 04:43:20 UTC 2023
one Mon Jan 16 04:43:21 UTC 2023
one Mon Jan 16 04:43:23 UTC 2023
one Mon Jan 16 04:43:24 UTC 2023
one Mon Jan 16 04:43:25 UTC 2023
one Mon Jan 16 04:43:26 UTC 2023
one Mon Jan 16 04:43:28 UTC 2023
one Mon Jan 16 04:43:29 UTC 2023
one Mon Jan 16 04:43:31 UTC 2023'
```
So we eventually see the `one`. This is not occurring in the failing test.

**Comment by ericvn** [comment] 2023-01-17 22:32
Looking at the 3 using-istio-dashboard timeouts, there seems to be an issue with all the workloads starting:
```
_verify_lines query_request_for_all_workloads "
+ details-v1.default
+ productpage-v1.default
+ ratings-v1.default
+ reviews-v1.default
+ reviews-v2.default
+ reviews-v3.default
"
```
In the 3 failures, some are missing. Examples:
```
local 'out=details-v1.default
productpage-v1.default'
```
or
```
local 'out=details-v1.default
productpage-v1.default
ratings-v1.default
reviews-v1.default
reviews-v2.default'
```

**Comment by ericvn** [comment] 2023-01-18 17:07
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12481/doc.test.profile_default_istio.io/1615507316650545152 is a time out failure in the tcp-shifting test with time extended to 75 mins.

**Comment by ericvn** [comment] 2023-01-20 14:52
https://github.com/istio/istio.io/pull/12494 will disable the flakiest tcp-shifting test.

**Comment by ericvn** [comment] 2023-01-20 17:57
https://github.com/istio/istio.io/pull/12494 was changed from disabling the test to make a change to hopefully help the test. Discussion in that PR.

**Comment by ericvn** [comment] 2023-01-20 20:01
Unfortunately, that didn't seem to fix the issue:
```
+++__verify_with_retry(): snip_apply_weightbased_tcp_routing_4
++++snip_apply_weightbased_tcp_routing_4(): kubectl get pod -l app=sleep -n istio-io-tcp-traffic-shifting -o 'jsonpath={.items..metadata.name}'
+++snip_apply_weightbased_tcp_routing_4(): export SLEEP=sleep-bc9998558-5xngk
+++snip_apply_weightbased_tcp_routing_4(): SLEEP=sleep-bc9998558-5xngk
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
+++snip_apply_weightbased_tcp_routing_4(): for i in {1..20}
+++snip_apply_weightbased_tcp_routing_4(): kubectl exec sleep-bc9998558-5xngk -c sleep -n istio-io-tcp-traffic-shifting -- sh -c '(date; sleep 1) | nc 172.18.7.112 31400'
++__verify_with_retry(): out='E0120 19:54:49.503134  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.503987  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.506018  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.507929  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
E0120 19:54:49.590281  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.591137  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.592988  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
E0120 19:54:49.594973  173451 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```

**Comment by ericvn** [comment] 2023-01-20 20:44
Some more investigating, and I'm wondering if the sleep pod is being terminated because of an earlier kubectl delete. Testing the removal of the delete in https://github.com/istio/istio.io/pull/12495.

**Comment by frankbu** [comment] 2023-01-20 22:02
The main clue here is that all of sudden `kubectl` starts getting this error:
```
E0120 19:54:49.503987  173438 memcache.go:238] couldn'\''t get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```
A Google search for `kubectl error memcache.go:238` gives a lot of talk about it, but no obvious answer. A couple of the discussions include suggestions to try `sudo swapoff -a`, so I wonder if maybe the problem is memory getting too low and then kubectl gets messed up because there's too much swapping?

**Comment by ericvn** [comment] 2023-01-25 15:23
Looking at test failures overnight we had roughly 5 in the  /tcp-traffic-shifting/gtwapi_test.sh/gtwapi_test.sh, a few were in some gtwapi cleanup checks (mirroring and ingress control) and one istio-dashboard. Hopefully the last is fixed one my PR merges. Still not sure on why kubectl or the oapiserver is misbehaving on the first mentioned test.

**Comment by ericvn** [comment] 2023-01-27 21:25
For now we are running this test with twice the memory we were before and can see if the gtwapi tests seem to flake less often.

**Comment by zirain** [comment] 2023-01-30 01:03
timeout again
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/12548/doc.test.profile_default_istio.io/1619800342872985600

**Closed** 2023-02-10 09:02 UTC
