### ISSUE TITLE
Can't checkout the code in Windows platform.

### ISSUE THREAD

**Issue by elkan1788** [istio/istio.io#9154] opened 2021-03-09 02:26 UTC
Hi ,

There I want to commit my Chinese translate content, but when I fork this repository and git clone to my computer which OS is windows, Then I meet the error that see this below:

```sh
"git" clone -v --recurse-submodules --progress "git@github.com:elkan1788/istio.io.git" "D:/GitRepos/istio.io"
Cloning into 'D:/GitRepos/istio.io'...
remote: Enumerating objects: 11, done.
remote: Counting objects:  36% (4/11)eceiving objects:   0% (1/123878)remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 123878 (delta 0), reused 5 (delta 0), pack-reused 123867R
Receiving objects: 100% (123878/123878), 129.39 MiB | 993.00 KiB/s, done.
Resolving deltas: 100% (72543/72543), done.
error: invalid path 'archive/v1.6/docs/reference/config/proxy_extensions/metadata_exchange.html./index.html'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Done

Press Enter or Esc to close console...
```

I try to checkout from HEAD that the error was happened again.  So is there anyone see this error same with me, please help me what is wrong with me and fix it ,  Thanks.

**Comment by ericvn** [comment] 2021-03-09 14:42
See #9050 which was the original PR to fix the issue. The problem is that the directory name is specified upstream, so we are working through the process to get that changed (done), the 1.6 branch to be update (PR waiting to be merged) and then rebuild the archive from 1.6 in the main branch.

**Comment by elkan1788** [comment] 2021-03-09 22:45
@ericvn  I waiting for this PR merge to do my translate work, hope there can get good news form this issue #9050 , Thank you.

**Comment by ericvn** [comment] 2021-03-10 16:53
@elkan1788 I had asked for someone to approve my PR yesterday and again today  so that I can continue with the next PR which once merged should fix the issue. At the mercy of maintainers to get things in at the moment.

**Comment by elkan1788** [comment] 2021-03-10 23:53
@ericvn Thanks for your work. I will keep focus on it .

**Comment by ericvn** [comment] 2021-03-11 16:37
Still waiting on approval for #9179. David said he would approve, but haven't seen that yet. Hopefully soon.

**Closed** 2021-03-11 18:09 UTC

**Comment by elkan1788** [comment] 2021-03-12 14:35
@ericvn  I see the code had change, Thanks a lot.
