### ISSUE TITLE
Issue with docs/setup/kubernetes/install/kubernetes/index.md

### ISSUE THREAD

**Issue by mukundha** [istio/istio.io#4064] opened 2019-04-27 06:34 UTC
Is Installation Step 1 specified on the page really needed?
```$ for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done```

look like `install/kubernetes/istio-demo.yaml` already includes all the CRDs

**Comment by frankbu** [comment] 2019-04-30 16:37
Closing as this is a duplicate of #3993

**Closed by frankbu** 2019-04-30 16:37 UTC
Labels: area/environments, kind/docs
